<?php

/**
 * @file
 * Contains exsismodule.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme_suggestions_HOOK() for contact form suggestion.
 */
function exsismodule_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  if (isset($variables['element']) && isset($variables['element']['#type']) && $variables['element']['#type'] == 'form') {
    $original_theme_hook = $variables['theme_hook_original'];

    $suggestions[] = $original_theme_hook . '__' . str_replace('-', '_', $variables['element']['#id']);
  }

  return $suggestions;
}



/**
 * Implements hook_theme().
 */
function exsismodule_theme() {
  return [
    'exsis_block' => [
      'variables' => [
        'form_exsis_user' => NULL,
        'form_exsis_user_modal' => NULL,
      ],
      'render element' => 'children',
    ],
  ];
}
